branch-defaults:
    master:
        environment: node-starter-env
environment-defaults:
    Streakoid-env:
        branch: null
        repository: null
global:
    application_name: Node starter
    default_ec2_keyname: null
    default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Node.js running on
        64bit Amazon Linux/4.8.3
    default_region: eu-west-2
    include_git_submodules: true
    instance_profile: null
    platform_name: null
    platform_version: null
    profile: eb-cli
    sc: git
    workspace_type: Application
deploy:
    artifact: dist/node-starter.zip
